database models e ajuste no requirements.txt
victormachadogp/vanilla-todo pull request #12
Opened 2021-02-28 21:03 UTC by cristiantcjti

Definição de Models Task e Tasklist. O Model Tasklist precisa ser finalizado. O campo 'active' esta sobre revisão do nome, possivelmente será alterado.

2021-02-28 21:15 UTC, jonathanmach approved these changes
Show de bola 👍

2021-02-28 21:20 UTC, jonathanmach commented on server/core/models.py
> +    active = models.BooleanField()
Precisamos apenas discutir sobre o nome desse campo. Acho que **completed** ou **is_completed** seria mais claro.

2021-02-28 21:25 UTC, jonathanmach commented on server/core/models.py
> +    id = models.IntegerField(primary_key=True)
Uma outra abordagem seria usar um UUID. Não acho que precisamos agora nem para esse projeto, mas é só para compartilhar informação.

2021-02-28 23:06 UTC, cristiantcjti commented on server/core/models.py
> +    active = models.BooleanField()
Sim, concordo. Vamos ver o que o @Daniel fala sobre. De repente ele até já altera lá no DER.

2021-02-28 23:06 UTC, cristiantcjti commented on server/core/models.py
> +    id = models.IntegerField(primary_key=True)
Show !!!

2021-03-02 11:52 UTC, LivSith commented on server/core/models.py
> +    active = models.BooleanField()
@cristiantcjti acho q vc marcou o Daniel errado no comentario ˆ_ˆ||

2021-03-02 12:09 UTC, LivSith requested changes
@cristiantcjti vc criou uma model... mas não gerou migration.

Para refletir no ambiente de todo mundo, precisa mandar suas migrations para q o banco de dados aplique o que vc criou na model... 
[Nota pessoal] por isso, sempre que falarmos de model, é bom só mandar para a master quando a model estiver finalizada.... (Ex. Tasklist está completo, gera migration e faz um commit, proximo passo, Task completa, gera migration e faz commit, (seria ruim ter uma migration referente a muitos campos) e o PullRequest é quando a tarefa está completa, pois não queremos código quebrado na maquina do amiguinho ;)

2021-03-02 14:11 UTC, Delatorrea requested changes
@cristiantcjti cria uma venv exclusiva para esse projeto, o requiremente que você gerou tem muitas dependências que não vamos usar... Depois de criar a venv você instala as dependencias com base no requirement.txt que está na master. Aí é só manter o essencial. Foi o que a @LivSith falou se mandar essa PR vai dar conflito da requirement,

2021-03-02 14:24 UTC, jonathanmach commented
> @cristiantcjti cria uma venv exclusiva para esse projeto, o requiremente que você gerou tem muitas dependências que não vamos usar... Depois de criar a venv você instala as dependencias com base no requirement.txt que está na master. Aí é só manter o essencial. Foi o que a @LivSith falou se mandar essa PR vai dar conflito da requirement,

Opa, quem gerou o `requirements.txt` foi eu, o @cristiantcjti estava corrigindo as dependencias nessa PR.

2021-03-02 14:29 UTC, Delatorrea commented
> > @cristiantcjti cria uma venv exclusiva para esse projeto, o requiremente que você gerou tem muitas dependências que não vamos usar... Depois de criar a venv você instala as dependencias com base no requirement.txt que está na master. Aí é só manter o essencial. Foi o que a @LivSith falou se mandar essa PR vai dar conflito da requirement,
> 
> Opa, quem gerou o `requirements.txt` cheio de dependecias erradas foi eu, o @cristiantcjti estava corrigindo as dependencias nessa PR.

Por isso que eu digo pra esquecer o que eu disse.  Desculpa ae!

2021-03-02 15:16 UTC, cristiantcjti commented on server/core/models.py
> +    active = models.BooleanField()
> @cristiantcjti acho q vc marcou o Daniel errado no comentario ˆ_ˆ||

O projeto já ganho fama internacional hahahahah

2021-03-02 15:23 UTC, cristiantcjti commented
> @cristiantcjti vc criou uma model... mas não gerou migration.
> 
> Para refletir no ambiente de todo mundo, precisa mandar suas migrations para q o banco de dados aplique o que vc criou na model...
> [Nota pessoal] por isso, sempre que falarmos de model, é bom só mandar para a master quando a model estiver finalizada.... (Ex. Tasklist está completo, gera migration e faz um commit, proximo passo, Task completa, gera migration e faz commit, (seria ruim ter uma migration referente a muitos campos) e o PullRequest é quando a tarefa está completa, pois não queremos código quebrado na maquina do amiguinho ;)

Showwwwww.... vou finalizar a model Task, gerar a migration de ambas e subir no RPO...Mas fiquei agora com uma dúvida, uma vez que se tem as models, cada pessoa não poderia gerar as migrations localmente em sua base para rodar? Ou uma vez criadas, é só passar para o amiguinho e ta tudo certo? @LivSith  ou  @jonathanmach ?

2021-03-04 22:14 UTC, LivSith approved these changes
Top... bora testar \0/

2021-03-04 22:14 UTC, merged