Adicionado overflow na div todos-container
victormachadogp/vanilla-todo pull request #17
Opened 2021-03-01 20:25 UTC by tiagolpires

2021-03-01 20:49 UTC, victormachadogp commented on client/main.css
> +  overflow: auto;
Shoow, aqui poderíamos usar `overflow-y: auto;` pra permitir que o elemento faça o scroll apenas na vertical

2021-03-01 21:04 UTC, victormachadogp approved these changes
Uma outra coisa que seria ideal pra acessibilidade é, se a area for permitir rolagem, o scroll deve ser visível, na verdade não sei porque não está ficando visível, mas no geral ficou muito bom

2021-03-01 21:22 UTC, tiagolpires commented on client/main.css
> +  overflow: auto;
Boa vou alterar para overflow-y

2021-03-01 21:26 UTC, tiagolpires commented on client/main.css
> +  display: none;
Eu que tirei a barra de rolagem aqui, eu achei que fico feio com ela
![image](https://user-images.githubusercontent.com/68790170/109561091-7710e100-7abb-11eb-93f3-b2052046dc0a.png)
Mas da pra deixar ela e estilizar depois se quiser

2021-03-01 23:22 UTC, victormachadogp commented on client/main.css
> +  display: none;
Sim, ficou assim porque seu container ta com 90% de width, mas vamos deixar sem por enquanto

2021-03-01 23:27 UTC, victormachadogp requested changes

2021-03-01 23:27 UTC, victormachadogp commented on client/main.css
> +  overflow-y: auto;
Na classe `.todos-container` podemos adicionar um `padding-bottom` de 85px para que o ultimo item da lista não fique atrás do campo Add new todo

2021-03-01 23:58 UTC, tiagolpires commented on client/main.css
> +  overflow-y: auto;
Verdade nem tinha reparado

2021-03-02 08:42 UTC, jonathanmach approved these changes
Parece ok 👍
Apenas uma dúvida sobre a cor em `rgb`.

2021-03-02 08:42 UTC, jonathanmach commented on client/main.css
> +  background-color: rgb(215 225 232);
Por que nao estamos usando a cor em hex aqui?

2021-03-02 10:56 UTC, victormachadogp commented on client/main.css
> +  background-color: rgb(215 225 232);
Boa ideia, podemos usar só hex pra padronizar

2021-03-02 10:59 UTC, tiagolpires commented on client/main.css
> +  background-color: rgb(215 225 232);
Verdade, eu tirei a transparência mas deixei em rgb. Vou mudar aqui

2021-03-02 11:11 UTC, victormachadogp approved these changes

2021-03-02 11:11 UTC, merged