#31 Adicionado Metodo Put para atualizar tasklist por id retornando JSON - CORRECAO
victormachadogp/vanilla-todo pull request #42
Opened 2021-03-10 21:09 UTC by danielfonseca

#31 Adicionado Metodo Put para atualizar tasklist por id retornando JSON - CORRECAO

2021-03-11 22:21 UTC, jonathanmach commented on server/core/views.py
> +           if f.name in data.keys():
O que seria `f`? Podemos usar um nome mais claro e explícito?

2021-03-11 22:26 UTC, jonathanmach commented on server/core/views.py
> +        for f in tasklist._meta.get_fields():
Ficou show de bola esse for por todos os fields de uma tasklist.
Apenas uma dúvida: se o front-end passasse um campo ID, isso atualizaria o id da tasklist também?
E se tivermos tasks associados às essa tasklist, o banco de dados iria lançar um database IntegrityError...

2021-03-11 22:27 UTC, jonathanmach commented on server/core/views.py
> +            return HttpResponse('"ERRO INTERNO - REPORTE O ADMINISTRADOR"', status=500)
Exception handling 👍👍

2021-03-21 01:04 UTC, danielfonseca commented
Código todo alterado para se adequar as dicas.

2021-03-21 11:55 UTC, jonathanmach commented on .gitignore
> +=======
Acho que faltou tratar alguns conflitos do git.
Esses ´<<<<<<< HEAD´  acontecem quando tem um merge conflict e o conflito precisa ser resolvido manualmente.

2021-03-21 12:05 UTC, jonathanmach requested changes
Show de bola!
Apenas alguns detalhes pequenos...

2021-03-21 12:05 UTC, jonathanmach commented on server/core/views.py
> +            return HttpResponse('ERRO - Id é invalido', status=408)
Status 408 quer dizer: Request Timeout.
Acho que nao se aplica nesse caso.

2021-03-26 18:52 UTC, LivSith commented
@danielfonseca quando fizer as correções me marca aqui, pq descobri q estava olhando no lugar errado!
## :sweat:

2021-03-28 20:39 UTC, danielfonseca commented
@LivSith @jonathanmach  atualizado!

2021-03-28 21:24 UTC, jonathanmach approved these changes

2021-03-28 21:24 UTC, jonathanmach commented on server/core/views.py
> +        return HttpResponse('OK', status=200)
Show.
Sempre costumo ver a API retornar o objeto atualizado, mas não sei dizer porque é uma boa prática. Acho que vale a pena deixar assim e talvez mais para a frente entenderemos porquê 👍

2021-04-01 20:02 UTC, cristiantcjti approved these changes

2021-04-01 20:02 UTC, cristiantcjti commented
@danielfonseca agora acredito que é só vc fazer o merge 👍🏻

2021-04-01 20:37 UTC, merged