Criado método POST Tasklist
victormachadogp/vanilla-todo pull request #44
Opened 2021-03-15 00:30 UTC by Delatorrea

#30

2021-03-15 18:39 UTC, jonathanmach commented on server/core/views.py
> +            tsk.title = data['title']
@Delatorrea, se o front-end enviar uma Tasklist sem nome, não deveríamos retornar um erro ao invés de criar um registro no banco sem nome?

2021-03-15 18:41 UTC, jonathanmach commented on server/server/urls.py
> -"""
Você não gosta dessa documentação no arquivo? 😂 
Eu acho uma boa pra quando você entra no arquivo e não se lembra exatamente das alternativas para declarar as rotas.

Eu votaria para mantermos... mas vamos ver o que os outros acham 👍

2021-03-15 18:41 UTC, Delatorrea commented on server/core/views.py
> +            tsk.title = data['title']
Sim. Você está certo. Ontem quando coloquei a cabela no travesseiro pensei nisso... Vou corrigir.

2021-03-15 18:44 UTC, Delatorrea commented on server/server/urls.py
> -"""
hehehe. Acredito ser minha falta de cultura... Confesso que me incomoda um monte de comentários.... Mas se for pra manter a gente mantem uai.

2021-03-26 18:49 UTC, LivSith commented on server/core/views.py
> +            tsk.title = data['title']
oi @Delatorrea quando fizer as alterações, ou se já fez, me marca aqui no comentário, pq hj eu descobri q olhava no lugar errado para ver as correções...  :grimacing: :flushed:

2021-05-02 23:40 UTC, Delatorrea commented
@LivSith 
@jonathanmach 
@cristiantcjti 

Fiz as alterações podem verificar por favor?

2021-05-04 12:04 UTC, LivSith approved these changes

2021-05-04 18:30 UTC, jonathanmach requested changes
Show! 🚀
Só um comentário sobre a docstring no arquivo correto

2021-05-04 18:30 UTC, jonathanmach commented on server/core/views.py
> +
Esse docstrings fazem parte do seguinte arquivo: `server/server/urls.py`

2021-05-04 18:32 UTC, Delatorrea commented on server/core/views.py
> +
Beleza. Vou corrigir.

2021-05-09 14:56 UTC, jonathanmach approved these changes

2021-05-09 15:01 UTC, merged