#33 Realizado GET para retorno das tasks de uma tasklist.
victormachadogp/vanilla-todo pull request #46
Opened 2021-03-21 22:11 UTC by cristiantcjti

2021-03-21 22:28 UTC, jonathanmach commented on server/core/views.py
> +        print("Testing....:", tasklist)
Jogar testes pro branch principal? 🤔

2021-03-21 22:30 UTC, jonathanmach commented on server/core/views.py
> +        return JsonResponse({'message': 'There is no task with the requested id'})
Acho que faltou especificar o http code, certo? Imagino que aqui ele iria mandar um 200 Ok por padrão, sendo que houve um problema na request.

2021-03-21 22:32 UTC, jonathanmach commented on server/core/views.py
> +    if request.method == "GET":
No decorator dessa função (`@require_http_methods(["GET"]) `) só  aceitamos GET. Esse `if` não fica redudante entao?

2021-03-22 11:11 UTC, cristiantcjti commented on server/core/views.py
> +        print("Testing....:", tasklist)
Opssssss my fault... hhahaha

2021-03-22 11:15 UTC, cristiantcjti commented on server/core/views.py
> +        return JsonResponse({'message': 'There is no task with the requested id'})
Quanto a isso não sei bem o que retornaria....estava falando com a @LivSith e acabamos decidindo deixar sem um específico pois imaginamos que dessa forma pegaríamos apenas o erro se não existir a task...de forma que só retornaríamos uma msg, mas não faço idéia se ele sempre retorna um status por padrão e se não definirmos um ele retorna 200. Mas de certa forma faz sentido sim colocar o 404 que é de not found poiiiiiiisssss de fato não achou né 😄 ...

2021-03-22 11:16 UTC, cristiantcjti commented on server/core/views.py
> +    if request.method == "GET":
Boa, vou dar uma arrumada.... 👍🏻

2021-03-22 18:29 UTC, jonathanmach requested changes

2021-03-22 18:29 UTC, jonathanmach commented on server/core/views.py
> +        tasks = Task.objects.get(id=tasklist_id)
> `GET /tasklists/:id/tasks/` - retorna todas as tasks de uma determinada tasklist

Essa query nao vai retornar todas as tasks de uma tasklist, vai? 🤔

2021-03-22 18:29 UTC, jonathanmach commented on server/core/views.py
> +        return JsonResponse({'message': 'There is no task with the requested id'})
Hmmm, o front-end precisa saber se a resposta da API foi  um sucesso ou não - e isso é feito principalmente através do http code.
Você retornando um código de sucesso quando na verdade houve uma exceção, vai causar um erro no front-end que vai tentar processar a response como se a lista de tasks tivesse sido retornada.

Senão me engano quando um http code não é informado, o padrão é sempre 200 Ok. Para testarmos é só fazer um request com um id inexistente 👍

2021-03-23 10:09 UTC, cristiantcjti commented on server/core/views.py
> +        return JsonResponse({'message': 'There is no task with the requested id'})
![image](https://user-images.githubusercontent.com/53867505/112129929-a8ef0200-8ba6-11eb-97aa-cca05acf81dc.png)

2021-03-23 10:10 UTC, cristiantcjti commented on server/core/views.py
> +        return JsonResponse({'message': 'There is no task with the requested id'})
Realmente retorna 200 mesmo que o id não exista.... Registrado e alterando 👍🏻

2021-03-23 11:12 UTC, cristiantcjti commented on server/core/views.py
> +        tasks = Task.objects.get(id=tasklist_id)
![image](https://user-images.githubusercontent.com/53867505/112137390-f2434f80-8bae-11eb-91b9-6ccc48047c88.png)

![image](https://user-images.githubusercontent.com/53867505/112137455-08511000-8baf-11eb-84da-5f60d165dc26.png)


Consegui retornar as tasks de uma tasklist. Porém, agora quando há uma request de uma tasklist que não tem tasks no banco, ele esta retornando uma lista vazia e não mais o erro . O 'except' não é executo pois o banco de fato retorna algo. Mas não consegui evocar uma exception nesse caso....acredito que teríamos de fazer uma lógica para tratar isso ou existe algo em Django? Pesquisei e o que chegou mais próximo foi isso : https://docs.djangoproject.com/en/3.1/_modules/django/core/exceptions/#EmptyResultSet 
Mas tentei implementar porém não executou a exception......

2021-03-23 21:35 UTC, jonathanmach approved these changes
Looks good! 
Por mim pode ir para master 👍

2021-03-23 21:35 UTC, jonathanmach commented on server/core/views.py
>      return JsonResponse(list(tasks), safe=False)
Dúvida: Pra que serve esse safe=False?

2021-03-23 21:35 UTC, jonathanmach commented on server/core/views.py
>  def tasklists_id_tasks(request, tasklist):
Talvez `tasklist` pudesse ser `tasklist_id` pra ser mais específico?

2021-03-23 22:17 UTC, cristiantcjti commented on server/core/views.py
>      return JsonResponse(list(tasks), safe=False)
![image](https://user-images.githubusercontent.com/53867505/112225965-51837d00-8c0c-11eb-8364-176050e11bda.png)

Acabei de descobrir hahaha

2021-03-23 22:18 UTC, cristiantcjti commented on server/core/views.py
>      return JsonResponse(list(tasks), safe=False)
Retornou esse erro ao rodar sem ele. Relação com a serealização

2021-03-25 13:32 UTC, cristiantcjti commented on server/core/views.py
>  def tasklists_id_tasks(request, tasklist):
Vou alterar hoje...show

2021-03-25 18:28 UTC, cristiantcjti commented
Acredito que agora é só a @LivSith aprovar que da para ir para master

2021-03-26 12:42 UTC, LivSith commented
Oi @cristiantcjti vc não vai atualizar com as alterações q o @jonathanmach apontou? Eu procurei os commits com alteração e não achei...

2021-03-26 14:14 UTC, cristiantcjti commented
Oi @LivSith , estão lá na aba 'Files Changed'

2021-03-26 14:16 UTC, cristiantcjti commented
Já subi tudo, se não achar me avisa tá....mas eu consigo ver as alterações e o @jonathanmach  tbm pq ele marcou como aprovado. Se não aparecer para vc temos que ver pq

2021-03-26 14:56 UTC, LivSith commented
Não tinha visto as abas "files changes", pensei q a ultima versão q fazemos push apareceria aqui na tela principal! Fazendo CR!!!

2021-03-26 15:00 UTC, LivSith approved these changes
Desculpa ae a falta de experiência :cold_sweat:
# Top :rocket:

2021-03-28 20:54 UTC, merged