Cris
victormachadogp/vanilla-todo pull request #49
Opened 2021-04-01 22:11 UTC by cristiantcjti

2021-04-02 15:06 UTC, jonathanmach requested changes
Apenas algumas considerações mínimas e um comentário sobre exception handling para revisarmos 👍

2021-04-02 15:06 UTC, jonathanmach commented on server/core/views.py
> +            logging.exception('Caught an error')
Estamos deixando de capturar e logar o erro aqui. Ou seja, qualquer erro que tivermos ao salvar essa task, a única informação que teremos no log será  `Caught an error`, que não diz nada sobre o real problema.

2021-04-03 21:22 UTC, cristiantcjti commented on server/core/views.py
> +from django.db.utils import IntegrityError
Esse IntegrityError é usado na linha 44 na rotina que o @danielfonseca fez.

2021-04-03 21:29 UTC, cristiantcjti commented on server/core/views.py
> +            logging.exception('Caught an error')
![image](https://user-images.githubusercontent.com/53867505/113491860-29b4d480-94aa-11eb-9d26-d168c6f82f54.png)

Agora fiquei em dúvida. Eu forcei um erro para ver o retorno. Esse log gerado e principalmente a última linha em destaque não é o retorno da função logging.exception? Na verdade, pesquisando ontem eu achei esse modo de tratar a exception...mas realmente não sei se é a melhor....o que vc acha de acordo com a foto ?

2021-04-03 21:29 UTC, cristiantcjti commented on server/core/views.py
> +import sys, json
Esse sys acho que podemos tirar .... vou testar

2021-04-04 22:37 UTC, cristiantcjti commented on server/core/views.py
> +            logging.exception('Caught an error')
@jonathanmach  A Lívia e eu refatoramos esse trecho de código na última atualização.

2021-04-05 15:52 UTC, jonathanmach requested changes

2021-04-05 15:52 UTC, jonathanmach commented on server/core/views.py
> +            return JsonResponse({'message': 'Error when saving'}, status=404)
404 quer dizer **Not found**. Qual seria outro http status code que se encaixaria melhor aqui?

2021-04-05 15:52 UTC, jonathanmach commented on server/core/views.py
> +            return JsonResponse({'message': ' Invalid Number of tasklist.'}, status=404)
Que tal usarmos algo como "Tasklist not found, ou,  Tasklist does not exist" ao invés  de "Invalid Number of tasklist"?

2021-04-05 15:52 UTC, jonathanmach commented on server/core/views.py
> +        return JsonResponse({'message': ' Invalid Number of task.'}, status=404)
Que tal usarmos algo como "Tasklist not found, ou,  Tasklist does not exist" ao invés  de "Invalid Number of tasklist"?

2021-04-05 15:52 UTC, jonathanmach commented on server/core/views.py
> +    return JsonResponse({"message": 'Task deleted'}, status=201)
201 quer dizer **Created**. Qual seria outro http status code que se encaixaria melhor aqui?

2021-04-07 11:04 UTC, cristiantcjti commented
Show vou rever esses pontos e subir as atualizações, possivelmente amanhã 👍🏻

2021-04-10 22:47 UTC, cristiantcjti commented
@jonathanmach  and @LivSith  realizei as mudanças sugeridas. Fico no aguardo do review.

2021-04-14 20:56 UTC, jonathanmach approved these changes
Excelete! 
Muito bom mesmo 👏

2021-04-14 20:56 UTC, jonathanmach commented on server/core/views.py
> +        except Exception as screen_error:
Por que essa variavel chama `screen_error` ? 🤔

2021-04-15 19:54 UTC, danielfonseca approved these changes
Muito em Cris, Excelente trabalho!

2021-04-15 19:58 UTC, cristiantcjti commented on server/core/views.py
> +        except Exception as screen_error:
HAHAHAH vou arrumar no próximo PR

2021-04-15 19:58 UTC, merged