#32 criado metodo delete de tasklist
victormachadogp/vanilla-todo pull request #51
Opened 2021-04-05 00:52 UTC by LivSith

2021-04-05 15:59 UTC, jonathanmach requested changes

2021-04-05 15:59 UTC, jonathanmach commented on server/server/urls.py
> +    path('tasklists/<int:tasklist_id>/delete', views.tasklist_delete),
Que tal seguirmos as melhores praticas de REST API design e não usar verbs na URL?

--- 

```
Never use CRUD function names in URIs
URIs should not be used to indicate that a CRUD function is performed. URIs should be used to uniquely identify resources and not any action upon them. HTTP request methods should be used to indicate which CRUD function is performed.
```
https://restfulapi.net/resource-naming/

```
3. Avoid using verbs in URIs
This is because HTTP verbs should be sufficient to describe the action being performed on the resource.
```
https://florimond.dev/blog/articles/2018/08/restful-api-design-13-best-practices-to-make-your-users-happy/

2021-04-06 01:10 UTC, LivSith commented on server/server/urls.py
> +    path('tasklists/<int:tasklist_id>/delete', views.tasklist_delete),
Show... @jonathanmach eu vou entender o q vc mandou e mudar!!! 
Valeu mesmo!

2021-05-05 01:01 UTC, closed without merging

2021-05-05 01:02 UTC, LivSith commented
Commitei uns arquivos errados -_-||